version: "3.7"
services:
    frontend:
        build: frontend
        depends_on:
            - mock-auth
        ports:
            - "3000:3000"
    mock-auth:
        image: ghcr.io/navikt/mock-oauth2-server:0.3.4
        ports:
            - "8080:8080"
        environment:
            - JSON_CONFIG_PATH=/mnt/conf/config.json
        volumes:
            - "./frontend/cypress/auth_server:/mnt/conf"
    cypress:
        build:
            context: ./
            dockerfile: ./frontend/cypress.Dockerfile
        depends_on:
            - frontend
        environment:
            - CYPRESS_RECORD_KEY
