name: Migrations

on:
  issue_comment:
    types: [created]

defaults:
  run:
    working-directory: backend/api

jobs:
  run_migrations:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/UpdateDatabase')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build project and dependencies
        run: dotnet build

      - name: Install dotnet ef tool
        run: dotnet tool install -g dotnet-ef

      - name: Update database
        run: dotnet ef database update --no-build
        env:
        # Overwriting azure credentials with database owner credentials to perform migration
          AzureAd__ClientId: bc77effc-135f-4c3e-9eed-ba2c36a9434d
          AzureAd__ClientSecret: ${{ secrets.AZUREAD__DATABASEOWNER__CLIENTSECRET }}
          ConnectionStrings__iPadDatabase: Server=tcp:fusion-test-sqlserver.database.windows.net,1433;Initial Catalog=Fusion-Apps-IPad-Service-DEV-DB;Persist Security Info=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

