name: Migrations

on:
  pull_request:
    branches: [ main ]
    paths: [ backend/api/database/migrations ]

defaults:
  run:
    working-directory: backend/api

jobs:
  run_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build project and dependencies
        run: dotnet build

      - name: Install dotnet ef tool
        run: dotnet tool install -g dotnet-ef

      - name: Update database
        run: dotnet ef database update --no-build
        env:
          AzureAd__ClientId: bc77effc-135f-4c3e-9eed-ba2c36a9434d
          AzureAd__ClientSecret: ${{ secrets.AZUREAD__DATABASEOWNER__CLIENTSECRET }}
